language: node_js
node_js:
  - 8
  - 7
  - 6
  - 5
  - 4
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: yarn run test-cov
after_script:
  - greenkeeper-lockfile-upload
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage